### ISSUE TITLE
Text based editing giving list index out of range error

### ISSUE THREAD

**Issue by harpavatkeerti** [luckyhzt/unicolor#5]
![image](https://user-images.githubusercontent.com/43930695/215328258-2c898dda-14a3-482e-8509-06d07ac21125.png)
Hi, thanks for the pretrained model, it's a very interesting work. I was trying some examples using the sample notebook you have provided in the repo. Stroke based and exemplar based cases work fine, but sometimes text based editing gives list index out of range error (screenshot attached). 

For this particular example, the prompts `Yellow tshirt` and `Pink mask` both give this error, but the prompt `Yellow tshirt and pink mask` doesn't give any error(although the result is not very good, result attached). 

Could you please help me with this? Thanks.
![masked_man](https://user-images.githubusercontent.com/43930695/215328574-f0523d88-c7fe-4047-81f0-af31e5232b3c.jpeg)
<img width="206" alt="image" src="https://user-images.githubusercontent.com/43930695/215328640-9fad778c-8a92-4728-b198-934ca87bc9aa.png">

**Comment by luckyhzt** [comment]
HI,

I think I forgot to convert all text to lower case, could you try use all lower case?

For the bad result, I think it is because the foreground and background in the image are not separated.

**Comment by harpavatkeerti** [comment]
Thanks @luckyhzt, it works after converting text to lower case.
